<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class VideosTableSeeder extends Seeder
{
    /**
     * Run the database seeding.
     */
    public function run()
    {
        DB::table('videos')->truncate();

        DB::table('videos')->insert(array(
            array(
                'title' => 'Painless Billing With Laravel and Stripe',
                'slug' => Str::slug('Painless Billing With Laravel and Stripe'),
                'video_id' => 'k9KKjxEq0Lg',
                'type' => 'youtube',
                'lang' => 'en',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Using Eloquent Outside of Laravel',
                'slug' => Str::slug('Using Eloquent Outside of Laravel'),
                'video_id' => 'L0g9ka5qaCc',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Fast Laravel Workflow With Generators',
                'slug' => Str::slug('Fast Laravel Workflow With Generators'),
                'video_id' => 'rmtjulbbSmY',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel Envoy',
                'slug' => Str::slug('Laravel Envoy'),
                'video_id' => 'ZI9vzxvERGI',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'PSR 4 Autoloading',
                'slug' => Str::slug('PSR 4 Autoloading'),
                'video_id' => 'FzdhnbM_0ug',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Gulp This',
                'slug' => Str::slug('Gulp This'),
                'video_id' => '6Jhgkp67GxI',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Test Databases In Memory (with Laravel)',
                'slug' => Str::slug('Test Databases In Memory (with Laravel)'),
                'video_id' => 'NB9KfQiHJO0',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Welcome to the Laravel Community',
                'slug' => Str::slug('Welcome to the Laravel Community'),
                'video_id' => '2_BKIhjHwS8',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Crazy Simple Pagination in Laravel',
                'slug' => Str::slug('Crazy Simple Pagination in Laravel'),
                'video_id' => 'lIEcyOUcNQk',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Better Error Monitoring with Bugsnag and Laravel',
                'slug' => Str::slug('Better Error Monitoring with Bugsnag and Laravel'),
                'video_id' => 'r4gK5uynk2s',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel Basic Authentication in 4 Minutes',
                'slug' => Str::slug('Laravel Basic Authentication in 4 Minutes'),
                'video_id' => 'FqDomWno2C0',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Understanding Fortrabbit Deployment Files',
                'slug' => Str::slug('Understanding Fortrabbit Deployment Files'),
                'video_id' => 'YvJiKI4IQ0Q',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel - How to Tail Log Files',
                'slug' => Str::slug('Laravel - How to Tail Log Files'),
                'video_id' => 'lP5yFWAt8Nk',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel and the N+1 Problem',
                'slug' => Str::slug('Laravel and the N+1 Problem'),
                'video_id' => 'swhWRMkpVsg',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel Artisan Commands 101',
                'slug' => Str::slug('Laravel Artisan Commands 101'),
                'video_id' => 'BviKET-QTEQ',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Form Model Binding in Laravel',
                'slug' => Str::slug('Form Model Binding in Laravel'),
                'video_id' => 'EJwxG3b9j9c',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'C Tags',
                'slug' => Str::slug('C Tags'),
                'video_id' => 'cE7jSTdE_uQ',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'View Composers in Laravel',
                'slug' => Str::slug('View Composers in Laravel'),
                'video_id' => 'X8yqmZtKOoY',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel - Understanding REST',
                'slug' => Str::slug('Laravel - Understanding REST'),
                'video_id' => 'rD82cZjTUZs',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel Queues With Iron and Fortrabbit',
                'slug' => Str::slug('Laravel Queues With Iron and Fortrabbit'),
                'video_id' => 'yeDCIognMRs',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Namespacing Primer (with Laravel)',
                'slug' => Str::slug('Namespacing Primer (with Laravel)'),
                'video_id' => 'yAzd7Ig1Wgg',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'From Zero to Deploy with Laravel',
                'slug' => Str::slug('From Zero to Deploy with Laravel'),
                'video_id' => '8rblX6Ta1-U',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel Setup For Newbs',
                'slug' => Str::slug('Laravel Setup For Newbs'),
                'video_id' => '9AU2QvkqkBM',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel Caching Ins and Outs',
                'slug' => Str::slug('Laravel Caching Ins and Outs'),
                'video_id' => 'Hl4-dftfc0o',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel Authentication Essentials',
                'slug' => Str::slug('Laravel Authentication Essentials'),
                'video_id' => 'msEwmVZ4wp4',
                'type' => 'youtube',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel 4 Update',
                'slug' => Str::slug('Laravel 4 Update'),
                'video_id' => '63892510',
                'type' => 'vimeo',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel 4 - Iron.io Push Queues & Closures',
                'slug' => Str::slug('Laravel 4 - Iron.io Push Queues & Closures'),
                'video_id' => '64703617',
                'type' => 'vimeo',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel 4 - IoC Controller Injection & Unit Testing',
                'slug' => Str::slug('Laravel 4 - IoC Controller Injection & Unit Testing'),
                'video_id' => '53029232',
                'type' => 'vimeo',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel 4 - Mail::queue and Mail::later',
                'slug' => Str::slug('Laravel 4 - Mail::queue and Mail::later'),
                'video_id' => '64779946',
                'type' => 'vimeo',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel 4 - Eloquent Collections & Polymorphic Relations',
                'slug' => Str::slug('Laravel 4 - Eloquent Collections & Polymorphic Relations'),
                'video_id' => '53183075',
                'type' => 'vimeo',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel 4 - Controllers & Filters',
                'slug' => Str::slug('Laravel 4 - Controllers & Filters'),
                'video_id' => '52964368',
                'type' => 'vimeo',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel 4 - IoC Container Basics',
                'slug' => Str::slug('Laravel 4 - IoC Container Basics'),
                'video_id' => '53009943',
                'type' => 'vimeo',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel 4 - Error Handling',
                'slug' => Str::slug('Laravel 4 - Error Handling'),
                'video_id' => '53445935',
                'type' => 'vimeo',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel 4 - Mail',
                'slug' => Str::slug('Laravel 4 - Mail'),
                'video_id' => '53701740',
                'type' => 'vimeo',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laravel 4 - Migrations & Seeding',
                'slug' => Str::slug('Laravel 4 - Migrations & Seeding'),
                'video_id' => '53701204',
                'type' => 'vimeo',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laracon (Day 1: Talk 2) Jeffrey Way',
                'slug' => Str::slug('Laracon (Day 1: Talk 2) Jeffrey Way'),
                'video_id' => '61104599',
                'type' => 'vimeo',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laracon (Day 1: Talk 1) Taylor Otwell',
                'slug' => Str::slug('Laracon (Day 1: Talk 1) Taylor Otwell'),
                'video_id' => '61063778',
                'type' => 'vimeo',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
            array(
                'title' => 'Laracon (Day 1 Talk 3) Kenny Meyers',
                'slug' => Str::slug('Laracon (Day 1 Talk 3) Kenny Meyers'),
                'video_id' => '61269747',
                'type' => 'vimeo',
                'lang' => 'tr',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ),
        ));
    }
}
